/* Generated by tmdb-codegen.ts. Do not edit. */

/** The path and query parameters of every TMDB v3 GET endpoint, by path template. */
export interface TmdbEndpoints {
	"/authentication": { path: {}; query: {} };
	"/account/{account_id}": {
		path: {
			"account_id": number;
		}; query: {
			"session_id"?: string;
		}
	};
	"/account/{account_id}/favorite/movies": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/account/{account_id}/favorite/tv": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/account/{account_id}/lists": {
		path: {
			"account_id": number;
		}; query: {
			"page"?: number;
			"session_id"?: string;
		}
	};
	"/account/{account_id}/rated/movies": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/account/{account_id}/rated/tv": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/account/{account_id}/rated/tv/episodes": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/account/{account_id}/watchlist/movies": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/account/{account_id}/watchlist/tv": {
		path: {
			"account_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
			"session_id"?: string;
			"sort_by"?: string;
		}
	};
	"/authentication/guest_session/new": { path: {}; query: {} };
	"/authentication/token/new": { path: {}; query: {} };
	"/certification/movie/list": { path: {}; query: {} };
	"/certification/tv/list": { path: {}; query: {} };
	"/movie/changes": {
		path: {}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/person/changes": {
		path: {}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/tv/changes": {
		path: {}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/collection/{collection_id}": {
		path: {
			"collection_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/collection/{collection_id}/images": {
		path: {
			"collection_id": number;
		}; query: {
			"include_image_language"?: string;
			"language"?: string;
		}
	};
	"/collection/{collection_id}/translations": {
		path: {
			"collection_id": number;
		}; query: {}
	};
	"/company/{company_id}": {
		path: {
			"company_id": number;
		}; query: {}
	};
	"/company/{company_id}/alternative_names": {
		path: {
			"company_id": number;
		}; query: {}
	};
	"/company/{company_id}/images": {
		path: {
			"company_id": number;
		}; query: {}
	};
	"/configuration": { path: {}; query: {} };
	"/configuration/countries": {
		path: {}; query: {
			"language"?: string;
		}
	};
	"/configuration/jobs": { path: {}; query: {} };
	"/configuration/languages": { path: {}; query: {} };
	"/configuration/primary_translations": { path: {}; query: {} };
	"/configuration/timezones": { path: {}; query: {} };
	"/credit/{credit_id}": {
		path: {
			"credit_id": string;
		}; query: {
			"language"?: string;
		}
	};
	"/discover/movie": {
		path: {}; query: {
			"certification"?: string;
			"certification.gte"?: string;
			"certification.lte"?: string;
			"certification_country"?: string;
			"include_adult"?: boolean;
			"include_video"?: boolean;
			"language"?: string;
			"page"?: number;
			"primary_release_year"?: number;
			"primary_release_date.gte"?: string;
			"primary_release_date.lte"?: string;
			"region"?: string;
			"release_date.gte"?: string;
			"release_date.lte"?: string;
			"sort_by"?: string;
			"vote_average.gte"?: number;
			"vote_average.lte"?: number;
			"vote_count.gte"?: number;
			"vote_count.lte"?: number;
			"watch_region"?: string;
			"with_cast"?: string;
			"with_companies"?: string;
			"with_crew"?: string;
			"with_genres"?: string;
			"with_keywords"?: string;
			"with_origin_country"?: string;
			"with_original_language"?: string;
			"with_people"?: string;
			"with_release_type"?: number;
			"with_runtime.gte"?: number;
			"with_runtime.lte"?: number;
			"with_watch_monetization_types"?: string;
			"with_watch_providers"?: string;
			"without_companies"?: string;
			"without_genres"?: string;
			"without_keywords"?: string;
			"without_watch_providers"?: string;
			"year"?: number;
		}
	};
	"/discover/tv": {
		path: {}; query: {
			"air_date.gte"?: string;
			"air_date.lte"?: string;
			"first_air_date_year"?: number;
			"first_air_date.gte"?: string;
			"first_air_date.lte"?: string;
			"include_adult"?: boolean;
			"include_null_first_air_dates"?: boolean;
			"language"?: string;
			"page"?: number;
			"screened_theatrically"?: boolean;
			"sort_by"?: string;
			"timezone"?: string;
			"vote_average.gte"?: number;
			"vote_average.lte"?: number;
			"vote_count.gte"?: number;
			"vote_count.lte"?: number;
			"watch_region"?: string;
			"with_companies"?: string;
			"with_genres"?: string;
			"with_keywords"?: string;
			"with_networks"?: number;
			"with_origin_country"?: string;
			"with_original_language"?: string;
			"with_runtime.gte"?: number;
			"with_runtime.lte"?: number;
			"with_status"?: string;
			"with_watch_monetization_types"?: string;
			"with_watch_providers"?: string;
			"without_companies"?: string;
			"without_genres"?: string;
			"without_keywords"?: string;
			"without_watch_providers"?: string;
			"with_type"?: string;
		}
	};
	"/find/{external_id}": {
		path: {
			"external_id": string;
		}; query: {
			"external_source": string;
			"language"?: string;
		}
	};
	"/genre/movie/list": {
		path: {}; query: {
			"language"?: string;
		}
	};
	"/genre/tv/list": {
		path: {}; query: {
			"language"?: string;
		}
	};
	"/guest_session/{guest_session_id}/rated/movies": {
		path: {
			"guest_session_id": string;
		}; query: {
			"language"?: string;
			"page"?: number;
			"sort_by"?: string;
		}
	};
	"/guest_session/{guest_session_id}/rated/tv": {
		path: {
			"guest_session_id": string;
		}; query: {
			"language"?: string;
			"page"?: number;
			"sort_by"?: string;
		}
	};
	"/guest_session/{guest_session_id}/rated/tv/episodes": {
		path: {
			"guest_session_id": string;
		}; query: {
			"language"?: string;
			"page"?: number;
			"sort_by"?: string;
		}
	};
	"/keyword/{keyword_id}": {
		path: {
			"keyword_id": number;
		}; query: {}
	};
	"/keyword/{keyword_id}/movies": {
		path: {
			"keyword_id": string;
		}; query: {
			"include_adult"?: boolean;
			"language"?: string;
			"page"?: number;
		}
	};
	"/list/{list_id}/item_status": {
		path: {
			"list_id": number;
		}; query: {
			"language"?: string;
			"movie_id"?: number;
		}
	};
	"/list/{list_id}": {
		path: {
			"list_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/movie/now_playing": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
			"region"?: string;
		}
	};
	"/movie/popular": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
			"region"?: string;
		}
	};
	"/movie/top_rated": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
			"region"?: string;
		}
	};
	"/movie/upcoming": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
			"region"?: string;
		}
	};
	"/movie/{movie_id}": {
		path: {
			"movie_id": number;
		}; query: {
			"append_to_response"?: string;
			"language"?: string;
		}
	};
	"/movie/{movie_id}/account_states": {
		path: {
			"movie_id": number;
		}; query: {
			"session_id"?: string;
			"guest_session_id"?: string;
		}
	};
	"/movie/{movie_id}/alternative_titles": {
		path: {
			"movie_id": number;
		}; query: {
			"country"?: string;
		}
	};
	"/movie/{movie_id}/changes": {
		path: {
			"movie_id": number;
		}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/movie/{movie_id}/credits": {
		path: {
			"movie_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/movie/{movie_id}/external_ids": {
		path: {
			"movie_id": number;
		}; query: {}
	};
	"/movie/{movie_id}/images": {
		path: {
			"movie_id": number;
		}; query: {
			"include_image_language"?: string;
			"language"?: string;
		}
	};
	"/movie/{movie_id}/keywords": {
		path: {
			"movie_id": string;
		}; query: {}
	};
	"/movie/latest": { path: {}; query: {} };
	"/movie/{movie_id}/lists": {
		path: {
			"movie_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/movie/{movie_id}/recommendations": {
		path: {
			"movie_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/movie/{movie_id}/release_dates": {
		path: {
			"movie_id": number;
		}; query: {}
	};
	"/movie/{movie_id}/reviews": {
		path: {
			"movie_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/movie/{movie_id}/similar": {
		path: {
			"movie_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/movie/{movie_id}/translations": {
		path: {
			"movie_id": number;
		}; query: {}
	};
	"/movie/{movie_id}/videos": {
		path: {
			"movie_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/movie/{movie_id}/watch/providers": {
		path: {
			"movie_id": number;
		}; query: {}
	};
	"/network/{network_id}": {
		path: {
			"network_id": number;
		}; query: {}
	};
	"/network/{network_id}/alternative_names": {
		path: {
			"network_id": number;
		}; query: {}
	};
	"/network/{network_id}/images": {
		path: {
			"network_id": number;
		}; query: {}
	};
	"/person/popular": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/person/{person_id}": {
		path: {
			"person_id": number;
		}; query: {
			"append_to_response"?: string;
			"language"?: string;
		}
	};
	"/person/{person_id}/changes": {
		path: {
			"person_id": number;
		}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/person/{person_id}/combined_credits": {
		path: {
			"person_id": string;
		}; query: {
			"language"?: string;
		}
	};
	"/person/{person_id}/external_ids": {
		path: {
			"person_id": number;
		}; query: {}
	};
	"/person/{person_id}/images": {
		path: {
			"person_id": number;
		}; query: {}
	};
	"/person/latest": { path: {}; query: {} };
	"/person/{person_id}/movie_credits": {
		path: {
			"person_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/person/{person_id}/tv_credits": {
		path: {
			"person_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/person/{person_id}/tagged_images": {
		path: {
			"person_id": number;
		}; query: {
			"page"?: number;
		}
	};
	"/person/{person_id}/translations": {
		path: {
			"person_id": number;
		}; query: {}
	};
	"/review/{review_id}": {
		path: {
			"review_id": string;
		}; query: {}
	};
	"/search/collection": {
		path: {}; query: {
			"query": string;
			"include_adult"?: boolean;
			"language"?: string;
			"page"?: number;
			"region"?: string;
		}
	};
	"/search/company": {
		path: {}; query: {
			"query": string;
			"page"?: number;
		}
	};
	"/search/keyword": {
		path: {}; query: {
			"query": string;
			"page"?: number;
		}
	};
	"/search/movie": {
		path: {}; query: {
			"query": string;
			"include_adult"?: boolean;
			"language"?: string;
			"primary_release_year"?: string;
			"page"?: number;
			"region"?: string;
			"year"?: string;
		}
	};
	"/search/multi": {
		path: {}; query: {
			"query": string;
			"include_adult"?: boolean;
			"language"?: string;
			"page"?: number;
		}
	};
	"/search/person": {
		path: {}; query: {
			"query": string;
			"include_adult"?: boolean;
			"language"?: string;
			"page"?: number;
		}
	};
	"/search/tv": {
		path: {}; query: {
			"query": string;
			"first_air_date_year"?: number;
			"include_adult"?: boolean;
			"language"?: string;
			"page"?: number;
			"year"?: number;
		}
	};
	"/trending/all/{time_window}": {
		path: {
			"time_window": string;
		}; query: {
			"language"?: string;
		}
	};
	"/trending/movie/{time_window}": {
		path: {
			"time_window": string;
		}; query: {
			"language"?: string;
		}
	};
	"/trending/person/{time_window}": {
		path: {
			"time_window": string;
		}; query: {
			"language"?: string;
		}
	};
	"/trending/tv/{time_window}": {
		path: {
			"time_window": string;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/airing_today": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
			"timezone"?: string;
		}
	};
	"/tv/on_the_air": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
			"timezone"?: string;
		}
	};
	"/tv/popular": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/tv/top_rated": {
		path: {}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/tv/{series_id}": {
		path: {
			"series_id": number;
		}; query: {
			"append_to_response"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/account_states": {
		path: {
			"series_id": number;
		}; query: {
			"session_id"?: string;
			"guest_session_id"?: string;
		}
	};
	"/tv/{series_id}/aggregate_credits": {
		path: {
			"series_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/{series_id}/alternative_titles": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/changes": {
		path: {
			"series_id": number;
		}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/tv/{series_id}/content_ratings": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/credits": {
		path: {
			"series_id": number;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/{series_id}/episode_groups": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/external_ids": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/images": {
		path: {
			"series_id": number;
		}; query: {
			"include_image_language"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/keywords": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/latest": { path: {}; query: {} };
	"/tv/{series_id}/lists": {
		path: {
			"series_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/tv/{series_id}/recommendations": {
		path: {
			"series_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/tv/{series_id}/reviews": {
		path: {
			"series_id": number;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/tv/{series_id}/screened_theatrically": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/similar": {
		path: {
			"series_id": string;
		}; query: {
			"language"?: string;
			"page"?: number;
		}
	};
	"/tv/{series_id}/translations": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/videos": {
		path: {
			"series_id": number;
		}; query: {
			"include_video_language"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/watch/providers": {
		path: {
			"series_id": number;
		}; query: {}
	};
	"/tv/{series_id}/season/{season_number}": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"append_to_response"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/account_states": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"session_id"?: string;
			"guest_session_id"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/aggregate_credits": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/season/{season_id}/changes": {
		path: {
			"season_id": number;
		}; query: {
			"end_date"?: string;
			"page"?: number;
			"start_date"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/credits": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/external_ids": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {}
	};
	"/tv/{series_id}/season/{season_number}/images": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"include_image_language"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/translations": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {}
	};
	"/tv/{series_id}/season/{season_number}/videos": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"include_video_language"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/watch/providers": {
		path: {
			"series_id": number;
			"season_number": number;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": number;
		}; query: {
			"append_to_response"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": number;
		}; query: {
			"session_id"?: string;
			"guest_session_id"?: string;
		}
	};
	"/tv/episode/{episode_id}/changes": {
		path: {
			"episode_id": number;
		}; query: {}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}/credits": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": number;
		}; query: {
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": string;
		}; query: {}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}/images": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": number;
		}; query: {
			"include_image_language"?: string;
			"language"?: string;
		}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}/translations": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": number;
		}; query: {}
	};
	"/tv/{series_id}/season/{season_number}/episode/{episode_number}/videos": {
		path: {
			"series_id": number;
			"season_number": number;
			"episode_number": number;
		}; query: {
			"include_video_language"?: string;
			"language"?: string;
		}
	};
	"/tv/episode_group/{tv_episode_group_id}": {
		path: {
			"tv_episode_group_id": string;
		}; query: {}
	};
	"/watch/providers/regions": {
		path: {}; query: {
			"language"?: string;
		}
	};
	"/watch/providers/movie": {
		path: {}; query: {
			"language"?: string;
			"watch_region"?: string;
		}
	};
	"/watch/providers/tv": {
		path: {}; query: {
			"language"?: string;
			"watch_region"?: string;
		}
	};
}
