import { writeFile } from "node:fs/promises";

/**
 * Generates TMDB's request types (paths, path parameters, query parameters)
 * from its published OpenAPI spec.
 *
 * Only GET operations are read, and response bodies are ignored: the spec
 * derives them from sample payloads, so every field is marked present and
 * non-null. Responses are validated by the Zod schemas in
 * `src/tmdb/resources.ts` instead.
 *
 * Run with `bun run tmdb:generate`.
 */
const specUrl = "https://developer.themoviedb.org/openapi/tmdb-api.json";

interface Parameter {
	name: string;
	in: "path" | "query" | "header";
	required?: boolean;
	schema?: {
		type?: string;
	};
}

interface Spec {
	paths: Record<string, { get?: { parameters?: Parameter[] } }>;
}

const response = await fetch(specUrl);
if (!response.ok) {
	throw new Error(`TMDB spec returned ${response.status}`);
}

const spec = (await response.json()) as Spec;

function typeOf(parameter: Parameter) {
	switch (parameter.schema?.type) {
		case "integer":
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		default:
			return "string";
	}
}

function members(parameters: Parameter[], location: Parameter["in"]) {
	return parameters
		.filter((parameter) => parameter.in === location)
		.map(
			(parameter) =>
				`${JSON.stringify(parameter.name)}${parameter.required ? "" : "?"}: ${typeOf(parameter)};`,
		);
}

const operations = Object.entries(spec.paths)
	.filter(([, item]) => item.get)
	.map(([path, item]) => {
		const parameters = item.get?.parameters ?? [];
		const block = (location: Parameter["in"]) =>
			members(parameters, location).length === 0
				? "{}"
				: `{\n${members(parameters, location).join("\n")}\n}`;
		return `${JSON.stringify(path.replace(/^\/3/, ""))}: { path: ${block("path")}; query: ${block("query")} };`;
	});

await writeFile(
	"src/tmdb/api.generated.ts",
	`/* Generated by tmdb-codegen.ts. Do not edit. */

/** The path and query parameters of every TMDB v3 GET endpoint, by path template. */
export interface TmdbEndpoints {\n${operations.join("\n")}\n}
`,
);
