name: publish packages

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: package.json

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://npm.pkg.github.com

            - run: bun install --frozen-lockfile
            - run: bun run --cwd packages/contracts build
            - run: bun run --cwd packages/sdk build
            - run: npm publish ./packages/contracts --access restricted
              env:
                  GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: npm publish ./packages/sdk --access restricted
              env:
                  GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
